name: Build

env:
  vcpkg_dir: '${{ github.workspace }}/vcpkg'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Get CMake
        uses: lukka/get-cmake@latest

    - name: Get vcpkg
      uses: lukka/run-vcpkg@latest
      with:
        setupOnly: true
    
    - name: Restore artifacts
      uses: lukka/run-vcpkg@v10
      id: runvcpkg

    - name: Bootstrap vcpkg
      run: |
        cd ${{ env.vcpkg_dir }}
        bootstrap-vcpkg.bat

    - name: Integrate vcpkg
      run: |
        cd ${{ env.vcpkg_dir }}
        vcpkg.exe integrate install

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DDIR_VCPKG_ROOT:PATH="${{ env.vcpkg_dir }}" -DVCPKG_MANIFEST_INSTALL:PATH="${{ env.vcpkg_dir }}\installed\" -DVCPKG_TARGET_TRIPLET:STRING="${{ env.arch }}-windows-static" -DCMAKE_TOOLCHAIN_FILE:PATH="${{ env.vcpkg_dir }}\scripts\buildsystems\vcpkg.cmake" -Wno-dev

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

